server:
  port: 9070
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  #    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#  需要加入clientid
security:
  oauth2:
    client:
      id:  admin
      client-secret: 123456